#!/bin/sh

case "$1" in
    start)
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        scull_unload
        module_unload faulty
        modprobe -r hello
        ;;
esac

exit 0
